---
title: "Simu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n <- 100000

set.seed(2350)
w0 <- rbinom(n, 1, .5)
table(w0)
```

```{r}
w1 <- rbinom(n, 1, 0.4 + 0.2*w0)
table(w1)
```

```{r}
probsel <- plogis(-1 + log(4)*w1 + log(4)*w0)
psel <- rbinom(n, 1, probsel)
svywt <- mean(probsel) / probsel
table(svywt)
```

```{r}
a <- rbinom(n, 1, 0.5)
table(a)
```

```{r}
z0 <- rbinom(n, 1, plogis(-log(2) * w1))
z1 <- rbinom(n, 1, plogis(log(4) - log(2)*w1))
z <- ifelse(a == 1, z1, z0)
table(z)
```

```{r}
m0 <- rbinom(n, 1, plogis(-log(3) - log(1.4)*w1))
m1 <- rbinom(n, 1, plogis(-log(3) + log(10) - log(1.4)*w1))
m <- ifelse(z == 1, m1, m0)
table(m)
```

```{r}
y <- rbinom(n, 1, plogis(log(1.2) + log(3) * z + log(3) * m - log(1.2) * w1 + log(1.2) * w1 * z))
table(y)
```

```{r}
dat <- data.frame(w1 = w1, a = a, z = z, m = m, y = y, psel = psel,
                  svywt = svywt, radid_person=seq(1, n, 1))
dat
```

```{r}
obsdat <- dat[dat$psel == 1, ]
obsdat <- obsdat[, -c(6)]
obsdat
```

```{r}
# write.csv(obsdat, "../Data/obsdat.csv")
```

```{r}
zmodel <- "z ~ a + w1"
mmodel <- "m ~ z + w1"
ymodel <- "y ~ m + z*w1"
qmodel <- "w1"
```

```{r}
# make gm
zfit <- glm(formula = zmodel, family = "binomial", data = obsdat)
mfit <- glm(formula = mmodel, family = "binomial", data = obsdat)

za0 <- predict(zfit, newdata = data.frame(w1 = obsdat$w1, a = 0), type = "response")
za1 <- predict(zfit, newdata = data.frame(w1 = obsdat$w1, a = 1), type = "response")

mz1 <- predict(mfit, newdata = data.frame(w1 = obsdat$w1, z = 1), type = "response")
mz0 <- predict(mfit, newdata = data.frame(w1 = obsdat$w1, z = 0), type = "response")
```

```{r}
gm <- mz1 * za0 + mz0 * (1 - za0)
gma1 <- mz1 * za1 + mz0 * (1 - za1)
```

```{r}
medtmle <- function(a, z, m, y, w, svywt, mmodel, ymodel, qmodel, gm, gma1) {
    set.seed(34059)
    
    datw <- w
    tmpdat <- data.frame(cbind(datw, a = a))
    
    # get initial fit Q_Y
    tmpdat$qyinit <- cbind(predict(glm(formula = ymodel, family = "binomial",
                                       data = data.frame(cbind(datw, z=z, m=m, y=y))),
                                   newdata = data.frame(cbind(datw, z=z, m=m)),
                                   type = "response"),
                           predict(glm(formula = ymodel, family = "binomial",
                                       data = data.frame(cbind(datw, z=z, m=m, y=y))),
                                   newdata = data.frame(cbind(datw, z=z, m=0)),
                                   type = "response"),
                           predict(glm(formula = ymodel, family = "binomial",
                                       data = data.frame(cbind(datw, z=z, m=m, y=y))),
                                   newdata = data.frame(cbind(datw, z=z, m=1)),
                                   type = "response"))
    
    psa1 <- I(a == 1) / mean(a)
    psa0 <- I(a == 0) / mean(1 - a)
    
    mz <- predict(glm(formula = mmodel, family = "binomial",
                      data = data.frame(cbind(datw, z=z, m=m))),
                  newdata = data.frame(cbind(datw, z=z)), type = "response")
    
    psm <- mz * m + (1 - mz) * (1 - m)
    
    tmpdat$ha1gma1 <- (m * gma1 + (1 - m) * (1 - gma1)) / psm * psa1 * svywt
    tmpdat$ha1gma0 <- (m * gm + (1 - m) * (1 - gm)) / psm * psa1 * svywt
    tmpdat$ha0gma0 <- (m * gm + (1 - m) * (1 - gm)) / psm * psa0 * svywt
    tmpdat$y <- y
    
    # target Q_Y
    # for E(Y_{1, gmastar})
    epsilonma1g0 <- coef(glm(y ~ 1 , weights = tmpdat$ha1gma0, offset = qlogis(qyinit[, 1]),
                             family = "quasibinomial", data = tmpdat))
    tmpdat$qyupm0a1g0 <- plogis(qlogis(tmpdat$qyinit[, 2]) + epsilonma1g0)
    tmpdat$qyupm1a1g0 <- plogis(qlogis(tmpdat$qyinit[, 3]) + epsilonma1g0)
    
    # for E(Y_{1, gma})
    epsilonma1g1 <- coef(glm(y ~ 1, weights = tmpdat$ha1gma1, offset = qlogis(qyinit[, 1]),
                             family = "quasibinomial", data = tmpdat))
    
    tmpdat$qyupm0a1g1 <- plogis(qlogis(tmpdat$qyinit[, 2]) + epsilonma1g1)
    tmpdat$qyupm1a1g1 <- plogis(qlogis(tmpdat$qyinit[, 3]) + epsilonma1g1)
    
    # for E(Y_{0, gmastar})
    epsilonma0g0 <- coef(glm(y ~ 1, weights = tmpdat$ha0gma0, offset = qlogis(qyinit[, 1]),
                             family = "quasibinomial", data = tmpdat))
    
    tmpdat$qyupm0a0g0 <- plogis(qlogis(tmpdat$qyinit[, 2]) + epsilonma0g0)
    tmpdat$qyupm1a0g0 <- plogis(qlogis(tmpdat$qyinit[, 3]) + epsilonma0g0)
    
    # estimate Q_M
    tmpdat$Qma1g0 <- tmpdat$qyupm0a1g0 * (1 - gm) + tmpdat$qyupm1a1g0 * gm
    tmpdat$Qma1g1 <- tmpdat$qyupm0a1g1 * (1 - gma1) + tmpdat$qyupm1a1g1 * gma1
    tmpdat$Qma0g0 <- tmpdat$qyupm0a0g0 * (1 - gm) + tmpdat$qyupm1a0g0 * gm
    
    # estimate Q_Z
    Qzfita1g0 <- glm(formula = paste("Qma1g0", qmodel, sep = "~"),
                     data = tmpdat[tmpdat$a == 1, ], family = "quasibinomial")
    Qzfita1g1 <- glm(formula = paste("Qma1g1", qmodel, sep = "~"),
                     data = tmpdat[tmpdat$a == 1, ], family = "quasibinomial")
    Qzfita0g0 <- glm(formula = paste("Qma0g0", qmodel, sep = "~"),
                     data = tmpdat[tmpdat$a == 0, ], family = "quasibinomial")
    
    Qza1g0 <- predict(Qzfita1g0, type = "response", newdata = tmpdat)
    Qza1g1 <- predict(Qzfita1g1, type = "response", newdata = tmpdat)
    Qza0g0 <- predict(Qzfita0g0, type = "response", newdata = tmpdat)
    
    # update Q_Z
    epsilonza1g0 <- coef(glm(Qma1g0 ~ 1, weights = psa1*svywt, offset = qlogis(Qza1g0),
                             family = "quasibinomial", data = tmpdat))
    epsilonza1g1 <- coef(glm(Qma1g1 ~ 1, weights = psa1*svywt, offset = qlogis(Qza1g1),
                             family = "quasibinomial", data = tmpdat))
    epsilonza0g0 <- coef(glm(Qma0g0 ~ 1, weights = psa1*svywt, offset = qlogis(Qza0g0),
                             family = "quasibinomial", data = tmpdat))
    
    Qzupa1g0 <- plogis(qlogis(Qza1g0) + epsilonza1g0)
    Qzupa1g1 <- plogis(qlogis(Qza1g1) + epsilonza1g1)
    Qzupa0g0 <- plogis(qlogis(Qza0g0) + epsilonza0g0)
    
    # estimate psi
    tmlea1m0 <- sum(Qzupa1g0 * svywt) / sum(svywt)
    tmlea1m1 <- sum(Qzupa1g1 * svywt) / sum(svywt)
    tmlea0m0 <- sum(Qzupa0g0 * svywt) / sum(svywt)
    
    # EIC
    tmpdat$qyupa1g0 <- plogis(qlogis(tmpdat$qyinit[, 1]) + epsilonma1g0)
    tmpdat$qyupa1g1 <- plogis(qlogis(tmpdat$qyinit[, 1]) + epsilonma1g1)
    tmpdat$qyupa0g0 <- plogis(qlogis(tmpdat$qyinit[, 1]) + epsilonma0g0)
    
    eic1a1g0 <- tmpdat$ha1gma0 * (tmpdat$y - tmpdat$qyupa1g0)
    eic2a1g0 <- psa1 * svywt * (tmpdat$Qma1g0 - Qzupa1g0)
    eic3a1g0 <- Qzupa1g0 - tmlea1m0
    eica1g0 <- eic1a1g0 + eic2a1g0 + eic3a1g0
    
    eic1a1g1 <- tmpdat$ha1gma1 * (tmpdat$y - tmpdat$qyupa1g1)
    eic2a1g1 <- psa1 * svywt * (tmpdat$Qma1g1 - Qzupa1g1)
    eic3a1g1 <- Qzupa1g1 - tmlea1m1
    eica1g1 <- eic1a1g1 + eic2a1g1 + eic3a1g1
    
    eic1a0g0 <- tmpdat$ha0gma0 * (tmpdat$y - tmpdat$qyupa0g0)
    eic2a0g0 <- psa1 * svywt * (tmpdat$Qma0g0 - Qzupa0g0)
    eic3a0g0 <- Qzupa0g0 - tmlea0m0
    eica0g0 <- eic1a0g0 + eic2a0g0 + eic3a0g0
    
    # estimands
    nde <- tmlea1m0 - tmlea0m0
    ndeeic <- eica1g0 - eica0g0
    vareic <- var(ndeeic) / nrow(tmpdat)
    
    nie <- tmlea1m1 - tmlea1m0
    nieeic <- eica1g1 - eica1g0
    varnieeic <- var(nieeic) / nrow(tmpdat)
    
    return(list("nde" = nde, "ndevar" = vareic, "nie" = nie, "nievar" = varnieeic))
}
```

```{r}
res <- medtmle(a = obsdat$a, z = obsdat$z, m = obsdat$m, y = obsdat$y,
               w = data.frame(w1 = obsdat$w1), svywt = obsdat$svywt,
               mmodel = mmodel, ymodel = ymodel, qmodel = qmodel,
               gm = gm, gma1 = gma1)

res
```

```{r}
sim.param.time.varying.L <- function(A.M.interaction = NULL) {
  # L0
  p_L0_male <- 0.5
  p_L0_parent_low_educ_lv <- 0.65
  
  # A: A0_ace <- rbinom( 0.05 + 0.04 * L0_male + 0.06 * L0_parent_low_educ_lv ) 
  b_A <- 0.05   # reference prevalence is 5%
  b_male_A <- 0.04  # + 0.04 for the effect of L0_male -> A0_ace
  b_parent_educ_A <- 0.06  # +0.06 for the effect of L0_parent_low_educ_lv -> A0_ace
  
  # L1: L1 <- rbinom( 0.30 - 0.05 * L0_male + 0.08 * L0_parent_low_educ_lv + 0.2 * A0_ace ) 
  b_L1 <- 0.30   # reference prevalence is 30%
  b_male_L1 <- -0.05  # - 0.05 for the effect of L0_male -> L1
  b_parent_L1 <- +0.08 # + 0.08 for the effect of L0_parent_low_educ_lv -> L1
  b_A_L1 <- +0.2 # +0.2 for the effect of A0_ace -> L1
  
  # M: M_smoking <- rbinom( 0.2 + 0.05 * L0_male + 0.06 * L0_parent_low_educ_lv + 0.2 * L1 + 0.1 * A0_ace ) 
  b_M <- 0.2 # reference prevalence is 20%
  b_male_M <- 0.05 # +0.05 for the effect of L0_male -> M_smoking
  b_parent_educ_M <- 0.06 # +0.06 for the effect of L0_parent_low_educ_lv -> M_smoking
  b_A_M <- 0.1 # +0.10 for the effect of A0_ace -> M_smoking
  b_L1_M <- 0.2 # +0.2 for the effect of L1 -> M_smoking
  
  # Y binary: rbinom( 0.10 + 0.06 * L0_male + 0.04 * L0_parent_low_educ_lv + 0.05 * A0_ace + 0.07 * L1 + 0.08 * M_smoking +
  #                   0.03 * A0_ace * M_smoking * A.M.inter ) 
  b_Y <- 0.1 # reference prevalence is 10%
  b_male_Y <- 0.06 # +0.06 for the effect of L0_male -> Y
  b_parent_educ_Y <- 0.04 # +0.04 for the effect of L0_parent_low_educ_lv -> Y
  b_A_Y <- 0.05 # 0.05 for the effect of A0_ace -> Y
  b_L1_Y <- 0.07 # +0.07 for the effect of L1 -> Y
  b_M_Y <- 0.08 # 0.08 for the effect of M_smoking -> Y
  b_AM_Y <- 0.03 # 0.03 for the interaction effect A0_ace * M_smoking -> Y
  
  # Y continuous: (75 - 1 * L0_male - 3 * L0_parent_low_educ_lv - 4 * A0_ace -3.5 * L1 - 9 * M_smoking + 
  #             -5 * A0_ace * M_smoking * A.M.inter ) + rnorm(N, mean = 0, sd = 10)
  mu_Y <- 75 # reference mean for QoL
  c_male_Y <- -1 # -1 for the effect of L0_male -> Y
  c_parent_educ_Y <- -3 # -3 for the effect of L0_parent_low_educ_lv -> Y
  c_A_Y <- -4 # -4 for the effect of A0_ace -> Y
  c_L1_Y <- -5 # -5 for the effect of L1 -> Y
  c_M_Y <- -9 # -9 for the effect of M_smoking -> Y
  c_AM_Y <- -5  # - 5 for the interaction effect A0_ace * M_smoking  -> Y
  sd_Y <- 10 # standard deviation of the residuals
  
  # A*M interaction ?
  A.M.inter <- A.M.interaction
  
  coef <- c(p_L0_male = p_L0_male, p_L0_parent_low_educ_lv = p_L0_parent_low_educ_lv, 
            b_A = b_A, b_male_A = b_male_A, b_parent_educ_A = b_parent_educ_A, 
            b_L1 = b_L1, b_male_L1 = b_male_L1, b_parent_L1 = b_parent_L1, b_A_L1 = b_A_L1,
            b_M = b_M, b_male_M = b_male_M, b_parent_educ_M = b_parent_educ_M,
            b_L1_M = b_L1_M, b_A_M = b_A_M, b_Y = b_Y, b_male_Y = b_male_Y,
            b_parent_educ_Y = b_parent_educ_Y, b_A_Y = b_A_Y, b_L1_Y = b_L1_Y,
            b_M_Y = b_M_Y, b_AM_Y = b_AM_Y, mu_Y = mu_Y, c_male_Y = c_male_Y,
            c_parent_educ_Y = c_parent_educ_Y, c_A_Y = c_A_Y, c_L1_Y = c_L1_Y,
            c_M_Y = c_M_Y, c_AM_Y = c_AM_Y, sd_Y = sd_Y, A.M.inter = A.M.inter)
  
  return(coef)
}
```

```{r}
gen.data.time.varying.L <- function(N, A.M.inter) { # input parameters are the sample size N and the presence of A*M interaction with A.M.inter = 0 or 1
  
  b <- sim.param.time.varying.L(A.M.interaction = A.M.inter)
  
  # baseline confounders: parent's educational level=L0_parent_low_educ_lv & sex=L0_male
  L0_male <- rbinom(N, size = 1, prob = b["p_L0_male"]) 
  L0_parent_low_educ_lv <- rbinom(N, size = 1, prob = b["p_L0_parent_low_educ_lv"])  
  
  # exposure: A0_ace
  A0_ace <- rbinom(N, size = 1, prob =  b["b_A"] + 
                     b["b_male_A"] * L0_male + 
                     b["b_parent_educ_A"] * L0_parent_low_educ_lv ) 
  
  # intermediate confounder between M_smoking and Y, not affected by A0 L1
  L1 <- rbinom(N, size = 1, prob = b["b_L1"] + 
                 b["b_male_L1"] * L0_male + 
                 b["b_parent_L1"] * L0_parent_low_educ_lv + 
                 b["b_A_L1"] * A0_ace )
  
  # mediator: M_smoking
  M_smoking <- rbinom(N, size = 1, prob = b["b_M"] + 
                        b["b_male_M"] * L0_male + 
                        b["b_parent_educ_M"] * L0_parent_low_educ_lv + 
                        b["b_A_M"] * A0_ace +
                        b["b_L1_M"] * L1) 
  
  # Y_death 
  Y_death <- rbinom(N, size = 1, prob = b["b_Y"] + 
                      b["b_male_Y"] * L0_male + 
                      b["b_parent_educ_Y"] * L0_parent_low_educ_lv + 
                      b["b_A_Y"] * A0_ace + 
                      b["b_L1_Y"] * L1 +
                      b["b_M_Y"] * M_smoking +
                      b["b_AM_Y"] * A0_ace * M_smoking * A.M.inter ) 
  
  # Y_qol 
  Y_qol <- ( b["mu_Y"] + 
               b["c_male_Y"] * L0_male + 
               b["c_parent_educ_Y"] * L0_parent_low_educ_lv +
               b["c_A_Y"] * A0_ace +
               b["c_L1_Y"] * L1 +
               b["c_M_Y"] * M_smoking + 
               b["c_AM_Y"] * A0_ace * M_smoking * A.M.inter ) + 
    rnorm(N, mean = 0, sd = b["sd_Y"])
  
  # data.frame
  data.sim <- data.frame(L0_male, L0_parent_low_educ_lv, A0_ace, L1, M_smoking, Y_death, Y_qol)
  
  return(data.sim)
}
```

```{r}
set.seed(1234)
data.sim <- gen.data.time.varying.L(N = n, A.M.inter = 0)

summary(data.sim)
```

```{r}
dat <- data.frame(w0 = data.sim$L0_male, w1 = data.sim$L0_parent_low_educ_lv,
                  a = data.sim$A0_ace, z = data.sim$L1, m = data.sim$M_smoking,
                  y = data.sim$Y_death, psel = psel, svywt = svywt,
                  radid_person = seq(1, n, 1))
dat
```

```{r}
obsdat <- dat[dat$psel == 1, ]
obsdat <- obsdat[, -c(7)]
obsdat
```

```{r}
zmodel <- "z ~ a + w1"
mmodel <- "m ~ z + w1"
ymodel <- "y ~ m + z*w1"
qmodel <- "w0 + w1"
```

```{r}
zfit <- glm(formula = zmodel, family = "binomial", data = obsdat)
mfit <- glm(formula = mmodel, family = "binomial", data = obsdat)

za0 <- predict(zfit, newdata = data.frame(w1 = obsdat$w1, a = 0), type = "response")
za1 <- predict(zfit, newdata = data.frame(w1 = obsdat$w1, a = 1), type = "response")

mz1 <- predict(mfit, newdata = data.frame(w1 = obsdat$w1, z = 1), type = "response")
mz0 <- predict(mfit, newdata = data.frame(w1 = obsdat$w1, z = 0), type = "response")
```

```{r}
gm <- mz1 * za0 + mz0 * (1 - za0)
gma1 <- mz1 * za1 + mz0 * (1 - za1)
```

```{r}
res <- medtmle(a = obsdat$a, z = obsdat$z, m = obsdat$m, y = obsdat$y,
               w = data.frame(w0 = obsdat$w0, w1 = obsdat$w1), svywt = obsdat$svywt,
               mmodel = mmodel, ymodel = ymodel, qmodel = qmodel,
               gm = gm, gma1 = gma1)

res
```

```{r}
library(tmle)

ate.tmle <- tmle(Y = obsdat$y, A = obsdat$a, W = data.frame(w0 = obsdat$w0, w1 = obsdat$w1),
                 Z = obsdat$z, Q.SL.library = c("SL.glm"), g.SL.library = c("SL.glm"),
                 V = 10, family = "binomial")
ate.tmle
```

```{r}
# library(stremr)
# 
# OData <- importData(obsdat, ID = "radid_person", covars = c("L0_parent_low_educ_lv"),
#                     TRT = "A0_ace", OUTCOME = "y", CENS = NULL, MONITOR = NULL,
#                     weights = "w1")
# 
# get_data(OData)
```

```{r}
expit <- function(x) {
  return(exp(x) / (1 + exp(x)))
}
```

```{r}
n <- 100
w1 <- rbinom(n, 1, 0.5)
w2 <- rbinom(n, 1, expit(0.4 + 0.2 * w1))
s <- rbinom(n, 1, expit(3 * w2 - 1))
a <- rbinom(n, 1, 0.5)
z <- rbinom(n, 1, expit(-3*a - 0.2*s + 2*w2 + 0.2*a*w2 - 0.2*a*s + 0.2*w2*s + 2*a*w2*s - 0.2))
m <- rbinom(n, 1, expit(z + 6*w2*z - 2*w2 - 2))
y <- rbinom(n, 1, expit(log(1.2) + log(4)*z - log(30)*m - log(1.2)*w2 - log(40)*w2*z))
```

```{r}
ymodel <- "y ~ z + m + w2 + w2*z"
mmodel <- "m ~ z + w2*z + w2"
zmodel <- "z ~ a + s + w2 + a*w2 + a*s + w2*s + a*w2*s"
qmodel <- "w1"
dat <- data.frame(w1 = w1, a = a, z = z, m = m, y = y, psel = psel,
                  svywt = svywt, radid_person=seq(1, n, 1))
dat
```

```{r}
obsdat <- dat[dat$psel == 1, ]
obsdat <- obsdat[, -c(6)]
obsdat
```

```{r}
res <- medtmle(a = obsdat$a, z = obsdat$z, m = obsdat$m, y = obsdat$y,
               w = data.frame(w1 = obsdat$w1), svywt = obsdat$svywt,
               mmodel = mmodel, ymodel = ymodel, qmodel = qmodel,
               gm = gm, gma1 = gma1)

res
```

