---
title: "TMLE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(kableExtra)
library(SuperLearner)

set.seed(7)
```

```{r}
generate_data <- function(n) {
    W1 <- rbinom(n, 1, 0.2)
    W2 <- rbinom(n, 1, 0.5)
    W3 <- round(runif(n, min = 2, max = 4))
    W4 <- round(runif(n, min = 0, max = 4))
    A <- rbinom(n, 1, plogis(-0.2 + 0.2*W2 + log(0.1*W3) + 0.3*W4 + 0.2*W1*W4))
    Y <- rbinom(n, size=1, prob= plogis(-1 + A - 0.1*W1 + 0.2*W2 + 0.3*W3 - 0.1*W4 + sin(0.1*W2*W4)))

    return(tibble(Y, W1, W2, W3, W4, A))
}
```

```{r}
n <- 1000
dat_obs <- generate_data(n)

kable(head(dat_obs), digits = 2, caption = "Simulated Data Set")
```

```{r}
sl_libs <- c('SL.glmnet', 'SL.ranger', 'SL.earth', 'SL.glm')
```

```{r}
Y <- dat_obs$Y
W_A <- dat_obs %>% select(-Y)
Q <- SuperLearner(Y = Y,
                  X = W_A,
                  family = binomial(),
                  SL.library = sl_libs
)
```

```{r}
Q_A <- as.vector(predict(Q)$pred)
```

```{r}
W_A1 <- W_A %>% mutate(A = 1)
Q_1 <- as.vector(predict(Q, newdata = W_A1)$pred)
```

```{r}
W_A0 <- W_A %>% mutate(A = 0)
Q_0 <- as.vector(predict(Q, newdata = W_A0)$pred)
```

```{r}
dat_tmle <- tibble(Y = dat_obs$Y, A = dat_obs$A, Q_A, Q_0, Q_1)
kable(head(dat_tmle), digits = 2, caption = "TMLE Algorithm after Step 1")
```

```{r}
ate_gcomp <- mean(dat_tmle$Q_1 - dat_tmle$Q_0)
ate_gcomp
```

```{r}
A <- dat_obs$A
W <- dat_obs %>% select(-Y, -A)
g <- SuperLearner(Y = A,
                  X = W,
                  family = binomial(),
                  SL.library = sl_libs
)
```

```{r}
g_w <- as.vector(predict(g)$pred)
H_1 <- 1 / g_w
```

```{r}
H_0 <- -1 / (1 - g_w)
```

```{r}
dat_tmle <-
    dat_tmle %>%
    bind_cols(H_1 = H_1,
              H_0 = H_0) %>%
    mutate(H_A = case_when(A == 1 ~ H_1,
                           A == 0 ~ H_0))
```

```{r}
kable(head(dat_tmle), digits = 2, caption = "TMLE Algorithm after Step 2")
```

```{r}
glm_fit <- glm(Y ~ -1 + offset(qlogis(Q_A)) + H_A, data = dat_tmle, family = binomial)
```

```{r}
eps<- coef(glm_fit)
```

```{r}
H_A <- dat_tmle$H_A
Q_A_update <- plogis(qlogis(Q_A) + eps * H_A)
```

```{r}
Q_1_update <- plogis(qlogis(Q_1) + eps * H_1)
```

```{r}
Q_0_update <- plogis(qlogis(Q_0) + eps * H_0)
```

```{r}
tmle_ate <- mean(Q_1_update - Q_0_update)
tmle_ate
```

```{r}
infl_fn <- (Y - Q_A_update) * H_A + Q_1_update - Q_0_update - tmle_ate
```

```{r}
tmle_se <- sqrt(var(infl_fn) / nrow(dat_obs))
```

```{r}
conf_low <- tmle_ate - 1.96 * tmle_se
conf_high <- tmle_ate + 1.96 * tmle_se
pval <- 2 * (1 - pnorm(abs(tmle_ate / tmle_se)))

kable(tibble(tmle_ate, conf_low, conf_high), digits = 3, caption = "TMLE Estimate of the ATE")
```

```{r}
tmle_fit <- tmle::tmle(Y = Y,
                       A = A,
                       W = W,
                       Q.SL.library = sl_libs,
                       g.SL.library = sl_libs
)

tmle_fit
```

